/* THIS FILE WAS AUTO GENERATED BY RIO. PLEASE DO NOT MODIFY */

#ifndef __RIO__AUTOGEN____H
#define __RIO__AUTOGEN____H

#define __RIO__DEFAULT__LANG__ en
#define rio(id) rio_lang(id, en)
#define rio_lang(id, lang) __RIO__ ## id ## __ ## lang ## __
#define __RIO__about__en__ "string language generator"
#define __RIO__help__en__ "usage: rio [flags] [options] <INPUT>\n\nflags:\n\t-h\t\tPrint help message\n\t-v\t\tPrint version message\n\noptions:\n\t-l\t\tSelected as the default language\n\t-o\t\tOutput filename"
#define __RIO__error__en__ "error"
#define __RIO__argument__en__ "argument error"
#define __RIO__lang__en__ "expected language option"
#define __RIO__output__en__ "expected output name"
#define __RIO__option__en__ "no such option"
#define __RIO__multiple__en__ "multiple files given"
#define __RIO__and__en__ "and"

#endif