/* THIS FILE WAS AUTO GENERATED BY RIO. PLEASE DO NOT MODIFY */

#ifndef __RIO__AUTOGEN____H
#define __RIO__AUTOGEN____H

#define __RIO__DEFAULT__LANG__ ja
#define rio(id) rio_lang(id, ja)
#define rio_lang(id, lang) __RIO__ ## id ## __ ## lang ## __
#define __RIO__about__en__ "string language generator"
#define __RIO__about__ja__ "文字列言語ジェネレーター"
#define __RIO__help__en__ "usage: rio [flags] [options] <INPUT>\n\nflags:\n\t-h\t\tPrint help message\n\t-v\t\tPrint version message\n\noptions:\n\t-l\t\tSelected as the default language\n\t-o\t\tOutput filename"
#define __RIO__help__ja__ "使用: rio [フラグ] [オプション] <入力>\n\nフラグ:\n\t-h\t\tヘルプ メッセージを印刷する\n\t-v\t\tバージョン メッセージの印刷\n\nオプション:\n\t-l\t\t既定の言語として選択\n\t-o\t\t出力ファイル名"
#define __RIO__error__en__ "error"
#define __RIO__error__ja__ "エラー"
#define __RIO__argument__en__ "argument error"
#define __RIO__argument__ja__ "引数エラー"
#define __RIO__lang__en__ "expected language option"
#define __RIO__lang__ja__ "予期される言語オプション"
#define __RIO__output__en__ "expected output name"
#define __RIO__output__ja__ "期待される出力名"
#define __RIO__option__en__ "no such option"
#define __RIO__option__ja__ "そのようなオプションはありません"
#define __RIO__multiple__en__ "multiple files given"
#define __RIO__multiple__ja__ "複数のファイルが与えられる"
#define __RIO__and__en__ "and"
#define __RIO__and__ja__ "と"

#endif